### ISSUE TITLE
Правки

### ISSUE THREAD

**Issue by alexanderem49** [deathwing00000/ERC20CryptonAcademy#1]
- [x] Многострочные комментарии пишутся таким образом:
```
/**
 * Текст
 *
 * Текст
 */
``` 
https://github.com/deathwing00000/ERC20CryptonAcademy/blob/21016cdc529386dc51cc9955dc4f39d388e81567/contracts/interfaces/EIP20.sol#L6

- [x] Добавить модификатор `override` к функциям, которые реализуются из интерфейса
https://github.com/deathwing00000/ERC20CryptonAcademy/blob/21016cdc529386dc51cc9955dc4f39d388e81567/contracts/TestToken.sol#L8

- [x] Вынести число 18 в `immutable` глобальную переменную и задать ей значение из конструктора
https://github.com/deathwing00000/ERC20CryptonAcademy/blob/21016cdc529386dc51cc9955dc4f39d388e81567/contracts/TestToken.sol#L85

- [x] Поменять модификатор `public` на `external` для функций, которые не вызываются внутри контракта
https://github.com/deathwing00000/ERC20CryptonAcademy/blob/21016cdc529386dc51cc9955dc4f39d388e81567/contracts/TestToken.sol#L48

- [x] Перед двоеточиями обычно пишется название контракта, а не название функции
https://github.com/deathwing00000/ERC20CryptonAcademy/blob/21016cdc529386dc51cc9955dc4f39d388e81567/contracts/TestToken.sol#L59

- [x] Оформление - перед фигурной скобкой должен быть пробел
https://github.com/deathwing00000/ERC20CryptonAcademy/blob/21016cdc529386dc51cc9955dc4f39d388e81567/contracts/TestToken.sol#L25

- [x] В .env не записывают название контракта - его тут можно захардкодить. Либо хотя бы отделить название контракта и название токена - далеко не всегда они совпадают.
https://github.com/deathwing00000/ERC20CryptonAcademy/blob/21016cdc529386dc51cc9955dc4f39d388e81567/scripts/deploy.ts#L15

- [x] Папка src/types - зачем? typechain не работает?

- [x] Чтобы получить название сети в которой ты работаешь, перенеси сюда список сетей как в hardhat.config.ts, но только ключ - id сети, а значение - название сети. Потом в коде получаешь id выбранной сети с помощью кода ниже. Кстати, у `net` будет ещё поле `name`, но я не уверен насколько оно будет соответствовать тому, что ожидается получить - возможно с ним можно обойтись и без списка сетей.
```
const net = await ethers.provider.getNetwork();
console.log(net.chainId);
```
https://github.com/deathwing00000/ERC20CryptonAcademy/blob/21016cdc529386dc51cc9955dc4f39d388e81567/tasks/deploy.ts#L11

- [x] Не всё на месте
https://github.com/deathwing00000/ERC20CryptonAcademy/blob/21016cdc529386dc51cc9955dc4f39d388e81567/tasks/index.ts#L1

- [x] Если у тебя токен будет с decimal не равным 18, количество токенов поплывёт. Используй `ethers.utils.parseUnits(amount, decimals)`. В остальных местах тоже.
https://github.com/deathwing00000/ERC20CryptonAcademy/blob/21016cdc529386dc51cc9955dc4f39d388e81567/tasks/approve.ts#L21

**Comment by deathwing00000** [comment]
1. "Многострочные комментарии пишутся таким образом"        -         поправил
2. Добавить модификатор override к функциям, которые реализуются из интерфейса           -          добавил
3. Вынести число 18 в immutable глобальную переменную и задать ей значение из конструктора                -                сделал (поправил деплой етц)
4. Поменять модификатор public на external для функций, которые не вызываются внутри контракта - поменял
5. Перед двоеточиями обычно пишется название контракта, а не название функции                    -                изменил(хотя для тестирования вариант с названием функции мне кажется более удобным)
6. Оформление - перед фигурной скобкой должен быть пробел                 -                      поправил
7. В .env не записывают название контракта - его тут можно захардкодить. Либо хотя бы отделить название контракта и название токена - далеко не всегда они совпадают. - добавил название контракта
8. Папка src/types - зачем? typechain не работает?         -           typechain запихивает туда types в соответствии с конфигурацией в hardhat.config.ts
9. Чтобы получить название сети в которой ты работаешь, перенеси сюда список сетей как в hardhat.config.ts, но только ключ - id сети, а значение - название сети. Потом в коде получаешь id выбранной сети с помощью кода ниже. Кстати, у net будет ещё поле name, но я не уверен насколько оно будет соответствовать тому, что ожидается получить - возможно с ним можно обойтись и без списка сетей.            -        реализовал через: const net = await hre.network.name;
10. Не всё на месте ERC20CryptonAcademy/tasks/index.ts              -         добавил
11. Если у тебя токен будет с decimal не равным 18, количество токенов поплывёт. Используй ethers.utils.parseUnits(amount, decimals). В остальных местах тоже.        -       поправил в тасках
